### ISSUE TITLE
Lots of silly things uploaded that ought not to be

### ISSUE THREAD

**Issue by Plazmaz** [WilliamMcCumstie/CS-419#2]
I noticed you've uploaded quite a few things to this repo that should **never** be public. The file that lead me here was https://raw.githubusercontent.com/WilliamMcCumstie/CS-419/26ca151b67e9cd81ff0aefd4e9717b684d008416/web-server/keys/key.pem, but https://github.com/WilliamMcCumstie/CS-419/blob/master/database-server/employeeRecognitionAPI.py also contains your mysql credentials. Basically, all of the information regarding this website is now public, forever, due to the design of GitHub. I strongly suggest changing your passwords and requesting a reissue of your SSL certificate if it wasn't a self-issued cert.

**Comment by Plazmaz** [comment]
Also, your repository, https://github.com/WilliamMcCumstie/Uni-work, is not, "Private Work". It is public and visible to any passerby. If you store credentials in that repo or other sensitive info, it too, is now forever public record. Again, committing the removal of these files **will not** remove them. All permalinks will still be valid, and there are many bots that scrape for that stuff.

**Comment by WilliamMcCumstie** [comment]
Thanks for the input.

The keys where previously self signed so I wasn't to concerned about security (as they couldn't be verified anyway). However as a matter of house keeping I have reissued the certificates and moved the file location. 

The /Uni-work profile was previously required to be public and doesn't contain any keys (they are buried in my root directory) so there is no sensitive information contain within it.

I wasn't aware that the database credentials where publicly viewable so thank you for picking that up. I will consult with my team member to update the credentials and remove them from public viewing.
